#Yaml config file for the genetic algorithm
#'cityCoordinates': [[-5,2],[3,-5],[7,3],[-7,-1.5]] # coordinates of cities in map frame (recommend using clicked_point)
# For priority example:
# 'cityCoordinates': [[7,3],[3,-5],[-7,-1.5],[-6,3]] # jackal race
'cityCoordinates': [[-2,4],[3,-5],[7,3],[-6,-2]] #Stuff coordinates
# 'cityCoordinates': [[6,-2],[-6,6],[7,-5],[6,-4]] #Stuff - straight line priority test
#'cityCoordinates': [[8,-11],[-8,-13],[-7,3],[8,0]] #Maze coordinates
# EnterAR map
# 'cityCoordinates': [[-5,-4],[0,7.5],[0,11],[-6,1]]
'numAgents': 2 # number of agents
'numCities': 4  # number of cities -> must match the number of cityCoordinates
'startPose': [[0,0],[0,1]]
'robotColors': [[0,0,1],[1,0,0],[0,1,0],[1,1,0]] # colors of assignments (blue, green, red, yellow, etc.)
# 'startPose': [[-8,-3],[0,0]] # 2 agents -> not used and updated once subscribed to jackal amcl pose
'priorities' : [0,3,0,3] # 0-regular,1-slightly important,2-important,3-emergency
'taskTimes' : [0,0,0,0] # time to complete each task
'precedence' : [[],[],[],[]] # precedence matrix
# 'precedence' : [[2,3],[],[3],[]] # precedence matrix - test in Stuff
'vels': [1,1] # max velocity of vehicles
'numGenerations': 50 # number of generations for GA
'populationSize': 50 # number of children in each generation
'mutationRate': 0.1 # mutation rate